package model;
// Generated 10/09/2015 03:38:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bateriasalida generated by hbm2java
 */
@Entity
@Table(name="bateriasalida"
    ,catalog="accesos"
)
public class Bateriasalida  implements java.io.Serializable {


     private Integer idBateria;
     private Estacion estacion;
     private String acceso;
     private Integer salidas;
     private Date fecha;
     private Set<Torniquetesalida> torniquetesalidas = new HashSet<Torniquetesalida>(0);

    public Bateriasalida() {
    }

	
    public Bateriasalida(Estacion estacion) {
        this.estacion = estacion;
    }
    public Bateriasalida(Estacion estacion, String acceso, Integer salidas, Date fecha, Set<Torniquetesalida> torniquetesalidas) {
       this.estacion = estacion;
       this.acceso = acceso;
       this.salidas = salidas;
       this.fecha = fecha;
       this.torniquetesalidas = torniquetesalidas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBateria", unique=true, nullable=false)
    public Integer getIdBateria() {
        return this.idBateria;
    }
    
    public void setIdBateria(Integer idBateria) {
        this.idBateria = idBateria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Estacion_idEstacion", nullable=false)
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }

    
    @Column(name="acceso", length=100)
    public String getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(String acceso) {
        this.acceso = acceso;
    }

    
    @Column(name="salidas")
    public Integer getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Integer salidas) {
        this.salidas = salidas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bateriasalida")
    public Set<Torniquetesalida> getTorniquetesalidas() {
        return this.torniquetesalidas;
    }
    
    public void setTorniquetesalidas(Set<Torniquetesalida> torniquetesalidas) {
        this.torniquetesalidas = torniquetesalidas;
    }




}


