package model;
// Generated 10/09/2015 03:38:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Torniquetesalida generated by hbm2java
 */
@Entity
@Table(name="torniquetesalida"
    ,catalog="accesos"
)
public class Torniquetesalida  implements java.io.Serializable {


     private Integer idTorniquete;
     private Bateriasalida bateriasalida;
     private String torniquete;
     private String fase;
     private Integer salida;

    public Torniquetesalida() {
    }

	
    public Torniquetesalida(Bateriasalida bateriasalida) {
        this.bateriasalida = bateriasalida;
    }
    public Torniquetesalida(Bateriasalida bateriasalida, String torniquete, String fase, Integer salida) {
       this.bateriasalida = bateriasalida;
       this.torniquete = torniquete;
       this.fase = fase;
       this.salida = salida;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTorniquete", unique=true, nullable=false)
    public Integer getIdTorniquete() {
        return this.idTorniquete;
    }
    
    public void setIdTorniquete(Integer idTorniquete) {
        this.idTorniquete = idTorniquete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Bateria_idBateria", nullable=false)
    public Bateriasalida getBateriasalida() {
        return this.bateriasalida;
    }
    
    public void setBateriasalida(Bateriasalida bateriasalida) {
        this.bateriasalida = bateriasalida;
    }

    
    @Column(name="torniquete", length=10)
    public String getTorniquete() {
        return this.torniquete;
    }
    
    public void setTorniquete(String torniquete) {
        this.torniquete = torniquete;
    }

    
    @Column(name="fase", length=10)
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }

    
    @Column(name="salida")
    public Integer getSalida() {
        return this.salida;
    }
    
    public void setSalida(Integer salida) {
        this.salida = salida;
    }




}


